@startuml
!pragma horizontalLineBetweenDifferentPackageAllowed

actor User as User1
actor User as User2
actor User as User3

[App] as APP1 #pink
[App] as APP2 #pink
node Redis {
   database DB as DB #blue
   artifact PubSub as PS #orange
}

User1 <-down-> APP1: HTTP
User2 <-down-> APP2: HTTP
User3 <-down-> APP2: HTTP
APP1 -up-> User1: WebSocket
APP2 -up-> User2: WebSocket
APP1 -up-> User3: WebSocket
APP1 <--> PS
APP2 <--> PS
APP1 <--> DB
APP2 <--> DB

@enduml